Feature of Extraction Technique
* To Reduce Curse of Dimentionality
* Transform Features and take the most effective one

Benefits
* Faster Execution
* Visualizaiton




In [67]:
import numpy as np
import pandas as pd
import plotly.express as px

In [68]:
np.random.seed(23)

mu_vec1 = np.array([0, 0, 0])
cov_mat1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample, columns=['feature1', 'feature2', 'feature3'])
df['target'] = 1

mu_vec2 = np.array([1, 1, 1])
cov_mat2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['feature1', 'feature2', 'feature3'])
df1['target'] = 0

df = pd.concat([df, df1], ignore_index=True)

df = df.sample(n=40)


In [69]:
df.head()

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [70]:
# Plotting

fig = px.scatter_3d(df, x='feature1', y='feature2', z='feature3', color='target')
fig.show()

In [71]:
# Step 1: Applying Standard Scaling

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [72]:
x

array([[-7.00808909e-01, -1.52558622e+00, -1.74915630e+00],
       [-2.24480873e-01, -1.01075678e+00,  4.91251361e-01],
       [-1.14564810e-02, -4.69345322e-02, -6.49615529e-01],
       [ 1.34229583e+00, -9.62723488e-01, -1.18416295e+00],
       [-2.57134993e+00, -2.99561164e-01, -5.40397642e-02],
       [ 8.67117739e-01,  9.35790500e-01, -4.26437402e-01],
       [ 1.56619581e+00, -2.19914261e-01,  4.61018902e-01],
       [-9.74766674e-02, -3.82240727e-01, -1.50416629e+00],
       [-1.01191670e+00,  9.54984015e-01, -6.61959948e-01],
       [ 2.09004923e+00, -7.57570343e-01,  1.73148981e+00],
       [-1.59495163e+00,  1.96573636e-01,  5.94105028e-01],
       [-6.69382831e-01, -1.99801138e+00, -4.26836402e-02],
       [ 2.04020404e-01, -4.15200709e-01, -1.27048700e+00],
       [-1.26266138e+00, -1.81870336e-02,  4.05425080e-01],
       [-4.27309418e-02,  8.23531488e-01, -6.77630557e-01],
       [ 1.08727791e+00,  3.55728104e+00, -6.57738712e-01],
       [-1.68465650e-01, -1.34904467e+00

In [73]:
# Step 2: Finding Covariance Matrix

covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])

print(covariance_matrix)

[[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [74]:
# Step 3: Finding Eigen_Vectors and Eigen_Values

eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)


In [75]:
pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [76]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)

new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1

In [77]:
fig = px.scatter(new_df, x='PC1', y='PC2', color='target')
fig.show()