In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

from sklearn.linear_model import Ridge


from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

In [26]:


data=load_diabetes()

In [27]:
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have bee

In [28]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df_target = pd.DataFrame(data.target, columns=["target"])

In [29]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [30]:
df_target.head()

target
0   151.0
1    75.0
2   141.0
3   206.0
4   135.0

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df, df_target, test_size=0.2, random_state=45)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((353, 10), (89, 10), (353, 1), (89, 1))

In [32]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [33]:
model.intercept_, model.coef_

(array([152.13623332]),
 array([[  23.45465406, -247.42747406,  492.1087518 ,  329.35876431,
         -970.79723039,  573.54295519,  182.42162368,  255.92168168,
          794.21609282,   89.32249214]]))

In [34]:
print("R2 Score:", r2_score(y_test, model.predict(X_test)))
print("RMSE:", np.sqrt(mean_squared_error(y_test, model.predict(X_test))))

R2 Score: 0.5188113124539249
RMSE: 48.72713760953253


In [36]:
# Regularization L2 | Ridge Regression

R = Ridge(alpha=100000)

In [37]:
R.fit(X_train,y_train)

Ridge(alpha=100000)

In [38]:
R.intercept_, R.coef_

(array([151.83287931]),
 array([ 0.00260126,  0.00057066,  0.00776597,  0.0060976 ,  0.00233864,
         0.00184724, -0.00513942,  0.0052716 ,  0.00734598,  0.00528629]))

In [39]:
print("R2 Score:", r2_score(y_test, R.predict(X_test)))
print("RMSE:", np.sqrt(mean_squared_error(y_test, R.predict(X_test))))

R2 Score: -0.00042490200441935855
RMSE: 70.25956272917782
