In [101]:
import pickle
import numpy as np

In [102]:
ohe_sex = pickle.load(open('/content/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('/content/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('/content/model.pkl', 'rb'))

In [103]:
# Sample user data
# Pclass/gender/age/Sibsp/Parch/Fare/Embarked

test_input = np.array([2, 'female', 22.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [104]:
test_input

array([[2, 'female', 22.0, 0, 0, 10.5, 'S']], dtype=object)

In [105]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [106]:
test_input_sex

array([[1., 0.]])

In [107]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [108]:
test_input_embarked

array([[0., 0., 1.]])

In [109]:
# test_input_age = test_input[:,2].reshape(1,1)

In [110]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5,2]],test_input_sex, test_input_embarked), axis=1)

In [111]:
test_input_transformed, test_input_transformed.shape

(array([[2, 0, 0, 10.5, 22.0, 1.0, 0.0, 0.0, 0.0, 1.0]], dtype=object),
 (1, 10))

In [112]:
clf.predict(test_input_transformed)

array([1])